version: "3.8"

services:
  db:
    image: postgres:14.1
    container_name: scoutingapp2022_dev_db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}

  backend:
    build:
      context: ./backend
      target: dev
    container_name: scoutingapp2022_dev_backend
    volumes:
      - ./backend:/app/backend
      - static:/app/backend/static
      - media:/app/backend/media
    environment:
      - ENV=dev
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DJANGO_SUPERUSER_USERNAME=${BACKEND_SU_USER}
      - DJANGO_SUPERUSER_PASSWORD=${BACKEND_SU_PASS}
      - DJANGO_SUPERUSER_EMAIL=${BACKEND_SU_EMAIL}
      - TBA_API_KEY
      - TBA_WEBHOOK_SECRET
      - CSRF_TRUSTED_ORIGINS
      - LOCALTUNNEL_SUBDOMAIN
      - BACKEND_PORT
      - APP_PORT
      - DEFAULT_CURRENT_EVENT_KEY
      - FRC_TEAM_NUMBER
      - FRC_YEAR
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: scoutingapp2022_dev_frontend
    volumes:
      - ./frontend:/app/frontend
      - next:/app/frontend/.next
      - node_modules:/app/frontend/node_modules
    ports:
      - "${APP_PORT}:3000"
    environment:
      - ENV=dev
      - NEXT_PUBLIC_TBA_API_KEY=${TBA_API_KEY}

  localtunnel:
    image: efrecon/localtunnel
    container_name: scoutingapp2022_dev_localtunnel
    links:
      - backend
    command: --local-host backend --port ${BACKEND_PORT} --subdomain=${LOCALTUNNEL_SUBDOMAIN}
    depends_on:
      - backend


volumes:
  next:
  node_modules:
  pgdata:
  static:
  media: