# Generated by Django 4.0.1 on 2022-02-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.PositiveSmallIntegerField()),
                ('team_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RobotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivetrain', models.CharField(choices=[('tank', 'Tank Drive'), ('mecanum', 'Mecanum Drive'), ('swerve', 'Swerve Drive'), ('hdrive', 'H-Drive'), ('butterfly', 'Butterfly Drive'), ('grasshopper', 'Grasshopper Drive'), ('kiwi', 'Kiwi Drive'), ('nona', 'Nonadrive'), ('octo', 'Octocanum Drive')], max_length=15)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_key', models.CharField(max_length=15, unique=True)),
                ('scouter_name', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouting.event')),
                ('team', models.ManyToManyField(to='scouting.Team')),
            ],
        ),
    ]
